networks:
  custom:
    ipam:
      config:
        - subnet: 10.5.0.0/16
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postresql/data
    networks:
      custom:

  googlesheetsapi:
    image: googlesheetsapi
    build:
      context: .
      dockerfile: GoogleSheetsAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=GoogleSheets
    ports:
      - 8000:8080
      - 8001:8080
    depends_on:
      - postgres
    networks:
      custom:
