@GoogleSheetsAPI_HostAddress = http://localhost:8001
@api-key = cJTUF8BhrNw7p1FnTAGMnFLSKhi0zqZeYuRlR4zwzqZ35peWyMU6jMB2Bo5p4J/Yfvnx7HkRsveTJZ+NcXVSaQ==
@spreadsheet_id = 1IETU7EI1UKkVGgaCcoz0R0cnX5tdme-6ealsXvtXR1k

POST {{GoogleSheetsAPI_HostAddress}}/write
Content-Type: application/json
Accept: application/json
x-api-key: {{api-key}}

{
    "spreadsheetId": "{{spreadsheet_id}}",
    "sheetname": "Sheet1",
    "range": "C8",
    "values": 
        ["John", "Doe", 26]
    
}
###
